spring.application.name=CRUD-PGC
spring.datasource.url=jdbc:postgresql://localhost:5432/PGC
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=crud_pgc
spring.datasource.password=crud_pgc
spring.jpa.hibernate.ddl-auto=validate
