CREATE TABLE IF NOT EXISTS Roles (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS Users (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_completo VARCHAR(255),
    username VARCHAR(255) UNIQUE NOT NULL,
    email VARCHAR(255),
    rol_id INT NOT NULL,
    direccion TEXT,
    latitud NUMERIC,
    longitud NUMERIC,
    fecha_nacimiento DATE,
    genero VARCHAR(50),
    password VARCHAR(255) NOT NULL,
    FOREIGN KEY (rol_id) REFERENCES Roles(id)
);

CREATE TABLE IF NOT EXISTS Combustibles (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS Precios (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    precio NUMERIC NOT NULL,
    id_estacion INT NOT NULL,
    id_combustible INT NOT NULL,
    FOREIGN KEY (id_combustible) REFERENCES Combustibles(id),
    FOREIGN KEY (id_estacion) REFERENCES Users(id)
);

CREATE TABLE IF NOT EXISTS Inventarios (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_estacion INT NOT NULL,
    id_combustible INT NOT NULL,
    cantidad_combustible NUMERIC NOT NULL,
    capacidad_maxima NUMERIC NOT NULL,
    nivel_minimo NUMERIC NOT NULL,
    FOREIGN KEY (id_combustible) REFERENCES Combustibles(id),
    FOREIGN KEY (id_estacion) REFERENCES Users(id)
);

CREATE TABLE IF NOT EXISTS Reglas (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_vehiculo VARCHAR(255) UNIQUE NOT NULL,
    precio NUMERIC NOT NULL CHECK(precio > 0),
    fecha TIMESTAMP,
    admin_id INT,
    FOREIGN KEY (admin_id) REFERENCES Users(id)
);

CREATE TABLE IF NOT EXISTS Subsidios (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subsidio BOOLEAN NOT NULL,
    porcentaje NUMERIC DEFAULT 0,
    user_id INT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES Users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Transacciones (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_vehiculo VARCHAR(255) NOT NULL,
    id_combustible INT NOT NULL,
    cantidad NUMERIC NOT NULL CHECK(cantidad > 0),
    total NUMERIC NOT NULL CHECK(total > 0),
    fecha TIMESTAMP,
    estacion_id INT,
    user_id INT,
    FOREIGN KEY (id_combustible) REFERENCES Combustibles(id),
    FOREIGN KEY (estacion_id) REFERENCES Users(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES Users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Entregas (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    placa VARCHAR(50) NOT NULL,
    id_combustible INT NOT NULL,
    cantidad NUMERIC NOT NULL CHECK(cantidad > 0),
    fecha TIMESTAMP,
    estado VARCHAR(50) NOT NULL DEFAULT 'PENDIENTE' CHECK(
        estado IN ('PENDIENTE','ENTREGADO','CONFIRMADO')
    ),
    estacion_destino_id INT NOT NULL,
    distribuidor_id INT,
    fecha_confirmacion TIMESTAMP,
    confirmado_por INT,
    FOREIGN KEY (id_combustible) REFERENCES Combustibles(id),
    FOREIGN KEY (estacion_destino_id) REFERENCES Users(id) ON DELETE CASCADE,
    FOREIGN KEY (distribuidor_id) REFERENCES Users(id) ON DELETE CASCADE,
    FOREIGN KEY (confirmado_por) REFERENCES Users(id)
);

CREATE OR REPLACE VIEW Movimientos AS 
SELECT t.id, t.tipo_vehiculo AS tipo, t.id_combustible, t.cantidad, t.total, t.fecha, t.estacion_id, t.user_id, 'SALIDA' AS tipo_movimiento 
FROM Transacciones t 
UNION ALL 
SELECT e.id, NULL::VARCHAR AS tipo, e.id_combustible, e.cantidad, NULL::NUMERIC AS total, e.fecha, e.estacion_destino_id AS estacion_id, e.distribuidor_id AS user_id, 'ENTRADA' AS tipo_movimiento 
FROM Entregas e 
WHERE e.estado = 'CONFIRMADO';
